version: '3.7'

services:
  ads-client:
    container_name: ads-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    env_file:
      - .env
    environment:
      - REACT_APP_ADS_MANAGEMENT_API_KEY=3MSq57l3vQHwiOO7lxCZyLsUBR6QpZ5lUScGXyFk
      - REACT_APP_ADS_MANAGEMENT_MAP_API_KEY=pb5X0Kv6rXI2AOATXViEDoBFYR9f3CU73abrt9tA
      - REACT_APP_REVERSE_GEOCODINNG_URI=https://rsapi.goong.io/Geocode
      - REACT_APP_PLACES_API=https://rsapi.goong.io/Place
      - REACT_APP_ADS_USER_URI=http://localhost:4000/v1/vhtt/user/ads-spots
      - PORT=3001
