version: '3'

services:
  adsmanagement:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:localdb@db:5432/adsmanagement
      - PORT=3000
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      - GOOGLE_MAILER_CLIENT_ID=624343219051-ochb66lnjs8nj6rjtuc7d584ecfb1bo6.apps.googleusercontent.com
      - GOOGLE_MAILER_CLIENT_SECRET=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
      - GOOGLE_MAILER_REFRESH_TOKEN=1//04ahBy5wXJkr7CgYIARAAGAQSNwF-L9IrYFdI3L7nbncGderb6WIZT7UeRON4p2LVUeDR2hMPOwd-pCQ7LXdtMbmP3qGGTIDoX2w
      - ADMIN_EMAIL_ADDRESS=group9notification@gmail.com
    ports:
      - '4000:3000'
    # volumes:
    #   - .:/usr/src/node-app
    # networks:
    #   - node-network
    command: bash -c "yarn db:schema && yarn seed && yarn start"

  db:
    container_name: db
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=adsmanagement
      - POSTGRES_PASSWORD=localdb
      - PGDATA=/var/lib/postgresql/data/adsmanagement/
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - '8080'
      - '5432'
    ports:
      - '5432:5432'
      - '8080:8080'
volumes:
  data:
