version: '3.7'

services:
  ads-admin:
    container_name: ads-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:4000
      - REACT_APP_API_URL=${REACT_APP_BACKEND_URL}/v1/
      - REACT_APP_ADS_MANAGEMENT_API_KEY=3MSq57l3vQHwiOO7lxCZyLsUBR6QpZ5lUScGXyFk
      - REACT_APP_ADS_MANAGEMENT_MAP_API_KEY=pb5X0Kv6rXI2AOATXViEDoBFYR9f3CU73abrt9tA
      - REACT_APP_REVERSE_GEOCODINNG_URI=https://rsapi.goong.io/Geocode
      - REACT_APP_PLACES_API=https://rsapi.goong.io/Place
      - REACT_APP_ADS_SPOTS_URI=${REACT_APP_BACKEND_URL}/v1/vhtt/ads-spots
